<?php
declare(strict_types=1);

namespace LAC\Modules\Tournament\Services;

class RandomTeamNames
{

    private const array CZ_ADJECTIVES = [
        'hořící',
        'schopný',
        'abnormální',
        'na palubě',
        'domorodý',
        'abortivní',
        'ohromující',
        'abrazivní',
        'náhlý',
        'nepřítomný',
        'absorbovaný',
        'absorbující',
        'abstraktní ',
        'absurdní',
        'hojné',
        'zneužívající',
        'přijatelné',
        'přístupné',
        'náhodné',
        'přesné',
        'kyselé',
        'kyselé',
        'akustické',
        'štiplavé',
        've skutečnosti',
        'ad hoc',
        'adamant',
        'adaptabilní',
        'závislý',
        'adhezivní',
        'přiléhající',
        'rozkošný',
        'dobrodružný',
        'strach',
        'agresivní',
        'agonizující',
        'příjemný',
        ' vpřed',
        'pootevřený',
        'alkoholik',
        'upozornění',
        'podobný',
        'živý',
        'údajný',
        'svůdný',
        'odměřený',
        'úžasný',
        'nejednoznačný',
        'ambiciózní',
        'sprostá',
        'pobavený',
        'zábavný',
        'starověký',
        'vzteklý',
        'animovaný',
        'otravný',
        'otravný',
        'úzkostný',
        'apatický',
        'vodní',
        'aromatický',
        'arogantní',
        'stydlivý',
        'aspirující',
        'rozmanitý',
        'úžasný',
        'atraktivní',
        'příznivý',
        'automatický',
        'dostupný',
        'průměrný',
        'probuzený',
        'vědomý',
        'úžasný',
        'strašný',
        'axiomatický',
        'špatný',
        'barbarský',
        'stydlivý',
        'oplzlý',
        'krásný',
        'slušný',
        'bojovný',
        'prospěšný',
        'prohnaný',
        'besní',
        'nejlepší',
        ' modrooký',
        'červenající se',
        'vroucí',
        'hrubý',
        'znuděný',
        'nudný',
        'skákavý',
        'bezmezný',
        'brainy',
        'drzý',
        'odvážný',
        'svalnatý',
        ' rozbitný',
        'vzdušný',
        'krátký',
        'jasný',
        'jasný',
        'široký',
        'zlomený',
        'hnědý',
        'hrbolatý',
        'statný',
        'rušný',
        'zaneprázdněný',
        'klecovitý',
        'kalkulující',
        'bezcitný',
        'klidný',
        'schopný',
        'rozmarný',
        'opatrný',
        'nedbalý',
        'starostlivý',
        'opatrný',
        'neustálý',
        'jistý',
        'proměnlivý',
        ' okouzlující',
        'levný',
        'veselý',
        'chemický',
        'hlavní',
        'dětský',
        'chladný',
        'rytířský',
        'baculatý',
        'chunky',
        'vlhký',
        'nóbl',
        'čistý',
        'jasný',
        'chytrý',
        'zamračený',
        'zataženo',
        'uzavřený',
        'nemotorný',
        'přeplněný',
        'koherentní',
        'studený',
        'barevný',
        'kolosální',
        'bojovný',
        ' pohodlný',
        'společný',
        'úplný',
        'složitý',
        'znepokojený',
        'odsouzený',
        'zmatený',
        'vědomý',
        'cooking',
        'cool',
        'kooperativní',
        'koordinovaný',
        'odvážný',
        'zbabělý',
        'podrážděný',
        'craven',
        'bláznivý',
        'strašidelný',
        'přeplněný',
        'krutý',
        'mazlivý',
        'kultivovaný',
        'těžkopádný',
        'zvědavý',
        'kudrnatý',
        'zakřivený',
        'křivky',
        'řezaný',
        'roztomilý',
        'roztomilý',
        'cynický',
        'daffy',
        'denně',
        'poškozený',
        'škodlivý',
        'vlhký',
        'nebezpečný',
        'jemný',
        'tmavý',
        'okázalý',
        'oslňující',
        'mrtvý',
        'ohlušující',
        'drahý',
        'debonair',
        'rozhodující',
        'decorous',
        'hluboké',
        'hluboce',
        'poražený',
        'vadný',
        'vzdorný',
        'delikátní',
        'lahodný',
        'rozkošný',
        'démonický',
        'deliriózní',
        'závislý',
        'depresivní',
        'vyšinutý',
        'popisný',
        'opuštěný',
        'detailní',
        'odhodlaný',
        'ďábelský',
        'didaktický',
        ' jiný',
        'obtížný',
        'pilný',
        'strašný',
        'špinavý',
        'nesouhlasný',
        'katastrofální',
        'diskrétní',
        'znechucený',
        'hnusný',
        'rozčarovaný',
        'postradatelný',
        'výrazný',
        'narušený',
        'divergentní',
        'závrať',
        'panovačný',
        'pochybný',
        'fádní',
        'drakonický',
        'dramatický',
        'pochmurný',
        'opilý',
        'suchý',
        'tupý',
        ' prašný',
        'prašný',
        'dynamický',
        'dysfunkční',
        'chtivý',
        'brzký',
        'uši drásající',
        'zemitý',
        'snadný',
        'jedlý',
        'ekonomický',
        'vzdělaný',
        'účinný',
        'zdatný',
        'osm',
        'elastický',
        'vznešený',
        'starší',
        'elektrický',
        'elegantní',
        'elfí',
        'elita',
        'rozpačitý',
        'významný',
        'prázdný',
        'očarovaný',
        'okouzlující',
        'povzbuzující',
        'snesitelný',
        'energický',
        'obrovský',
        'zábavný',
        'nadšený',
        'závistivý',
        'rovný',
        'rovný',
        'vzpřímený',
        'nerovný',
        ' éterický',
        'prchavý',
        'úhybný',
        'rovnoměrný',
        'výborný',
        'vzrušený',
        'vzrušující',
        'exkluzivní',
        'exotický',
        'drahý',
        'extra-velký',
        'extra-malý',
        'bujarý',
        'jásající',
        'báječný',
        'vybledlý',
        'mdlý',
        'spravedlivý',
        'věrný',
        'klamný',
        'falešný',
        'známý',
        'slavný',
        'fanatický',
        ' fantazijní',
        'fantastický',
        'daleko',
        'vzdálený',
        'fascinovaný',
        'rychlý',
        'tlustý',
        'chybný',
        'bojácný',
        'nebojácný',
        'slabý',
        'předstíraný',
        ' žena',
        'úrodný',
        'slavnostní',
        'málo',
        'divoký',
        'špinavý',
        'jemný',
        'vybíravý',
        'první',
        'pět',
        'fixní',
        'flagrantní',
        'potrhaný',
        'honosný',
        'plochý',
        'bezchybný',
        'choulostivý',
        'flippant',
        'květinový',
        'načechraný',
        'vlající',
        'pěnivý',
        'hloupý',
        'předcházející',
        'zapomnětlivý',
        ' šťastný',
        'čtyři',
        'křehký',
        'křehký',
        'free',
        'freezing',
        'frequent',
        'fresh',
        'freful',
        'friendly',
        'ustrašený',
        'děsivý',
        'plný',
        'nemotorný',
        'funkční',
        'vtipný',
        'chlupatý',
        'pokrytý',
        'budoucnost',
        'futuristický',
        'rozmazaný',
        'gabby',
        'gainful',
        'gamy',
        'gaping',
        'garrulouous',
        'gaudy',
        'General',
        ' jemný',
        'obří',
        'závratný',
        'nadaný',
        'gigantický',
        'okouzlující',
        'zářící',
        'třpytivý',
        'třpytivý',
        'nádherný',
        'lesklý',
        'zbožný',
        'dobrý',
        'praštěný',
        'nádherný',
        'půvabný',
        'grandiózní',
        'vděčný',
        'gratis',
        'šedý',
        'mastný',
        'skvělý',
        'chamtivý',
        'zelený',
        'šedý',
        'truchlící',
        'groteskní',
        'mrzutý',
        'střežený',
        'bez viny',
        'důvěřivý',
        'návalový',
        'hrdelní',
        'obvyklá',
        'napůl',
        'posvěcený',
        'zastavení',
        'hezký',
        'hezký',
        'šikovný',
        'visící',
        'nešťastný',
        'šťastný',
        'těžko',
        'harmonický',
        'drsný',
        'nenávistný',
        'opojný',
        'zdravý',
        'srdcervoucí',
        'nebeský',
        'těžký',
        'pekelný',
        'užitečný',
        'pomocný',
        'černý',
        'modrý',
        'hnědý',
        'šedý',
        'zelený',
        'oranžový',
        'purpurový',
        'červený',
        'bílý',
        'žlutý',
        'velký',
        'hluboký',
        'dlouhý',
        'úzký',
        'krátký',
        'malý',
        'vysoký',
        'tlustý',
        'tenký',
        'široký',
        'tvary',
        'kruhový',
        'rovný',
        'čtvercový',
        'trojúhelníkový',
        'hořký',
        'čerstvý',
        'slaný',
        'kyselý',
        'pikantní',
        'sladký',
        'špatný',
        'čistý',
        'tmavý',
        'obtížný',
        'špinavý',
        'suchý',
        'snadný',
        'prázdný',
        'drahý',
        'rychlý',
        'zahraniční',
        'plný',
        'dobrý',
        'tvrdý',
        'těžký',
        'levný',
        'světlý',
        'místní',
        'nový',
        'hlučný',
        'starý',
        'správný',
        'pomalý',
        'měkký',
        'velmi',
        'slabý',
        'mokrý',
        'špatný',
        'mladý',
        'přátelský',
        'zdravý',
        'nádherný',
        'poctivý',
        'šťastný',
        'mocný',
        'klidný'
    ];

    private const array TOURNAMENT_NAMES = [
        'Zabijáci',
        'Killeři',
        'Střelci',
        'Hereos',
        'Hrdinové',
        'Snipers',
        'Vyvolení',
        'Nepřemožitelní',
        'Vojáci',
        'Četa 248',
        'Ninjové',
        'Vítězové',
        'Ostrostřelci',
        'Modří',
        'Červení',
        'Zelení',
        'Černí',
        'Bílí',
        'Borci',
        'Bruteforce',
        'Hvězdná pěchota',
        'Captains',
        'Laser killers',
        'Laser kluci',
        'Mimoni',
        'Terminátoři',
        'Draci',
        'Mimozemšťani',
        'Assassíni',
        'Sebevražedný oddíl',
        'Rebelelové',
        'Tygři',
        'Slaboši',
        'Špioni',
        'Agenti',
        'Lenoši',
        'Vítězové',
        'Bojovníci',
        'Teletabís',
        'Šmoulové',
    ];

    /**
     * @var string[]
     */
    private array $czechNouns {
        get {
            if (!isset($this->czechNouns)) {
                $ch = \curl_init('http://slova.cetba.eu/generate.php?number=100');
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                $result = curl_exec($ch);
                $this->czechNouns = array_map('trim', explode('|', $result));
            }
            return $this->czechNouns;
        }
    }

    public function generate(): string
    {
        // Generate a set of random tournament names and choose one
        $names = [];

        // Some random predefined tournament names
        for ($i = 0; $i < 3; $i++) {
            $names[] = self::TOURNAMENT_NAMES[array_rand(self::TOURNAMENT_NAMES)];
        }

        // Some random combinations of adjectives and nouns
        for ($i = 0; $i < 5; $i++) {
            $adjective = self::CZ_ADJECTIVES[array_rand(self::CZ_ADJECTIVES)];
            $noun = $this->czechNouns[array_rand($this->czechNouns)];
            $names[] = ucfirst($adjective) . ' ' . ucfirst($noun);
        }

        // Some random combinations of adjectives and predefined tournament names
        for ($i = 0; $i < 3; $i++) {
            $adjective = self::CZ_ADJECTIVES[array_rand(self::CZ_ADJECTIVES)];
            $tournamentName = self::TOURNAMENT_NAMES[array_rand(self::TOURNAMENT_NAMES)];
            $names[] = ucfirst($adjective) . ' ' . $tournamentName;
        }

        // Return a random name from the generated set
        return $names[array_rand($names)];
    }

}